### ISSUE TITLE
`shortname` casing different from folder casing

### ISSUE THREAD

**Issue by neil-morrison44** [Mazamars312/Analogue-Amiga#11]
Hi,

Great work on the core (again)

One thing is tripping up Pocket Sync a little:

> The core folder name should follow this convention: AuthorName.CoreName where AuthorName and CoreName correspond to author and shortname in core.json respectively.

https://www.analogue.co/developer/docs/core-definition-files#folder-naming-convention

The folder ends up as `Mazamars312.Amiga` vs `amiga` in the shortname field

**Comment by Mazamars312** [comment]
Fair call. This is why I at times, "hate" Unix/Linux file systems. Windows make this too easy. LOL

Ill work on this on the next build and test on the next build 0.0.6. If you hit me up on discord I can get a 'pre' release done first so you can test

**Comment by Tolaris** [comment]
I can create a pull request to rename Analogue-Amiga/dist/assets/ to Analogue-Amiga/dist/Assets/ and the same for .../platforms to .../Platforms. But this will probably require you to manually do a two-step on Windows:

```
move assets Assets2
move Assets2 Assets
move platforms Platforms2
move Platforms2 Platforms
```

Would you like me to send the request?

**Comment by Mazamars312** [comment]
I can change the folders in the next build. It would tho require some people to check their folders.

Could you please check for me (BTW I have made the Amiga name in my core name with a capital as well)
![image](https://user-images.githubusercontent.com/29040078/206870805-e62e8ec8-f33d-4214-b106-efd8749612b5.png)
![image](https://user-images.githubusercontent.com/29040078/206870821-b41ef0c2-d9e1-4921-9718-1c4578aa9a01.png)
![image](https://user-images.githubusercontent.com/29040078/206870837-2bd9eb28-07a7-4cf7-9fb0-0bbd8aae0b67.png)
![image](https://user-images.githubusercontent.com/29040078/206870845-a35ae889-64da-4960-8a41-eaefc8c2c539.png)
![image](https://user-images.githubusercontent.com/29040078/206870851-9d9726f3-2db5-4d81-b3f0-bee82361be1f.png)
![image](https://user-images.githubusercontent.com/29040078/206870857-f68dd6b5-c3c7-4138-a21e-462cad2844e7.png)

**Comment by Tolaris** [comment]
Yes, the way those folders are capitalised matches mine.

**Comment by Mazamars312** [comment]
Been released now

**Comment by neil-morrison44** [comment]
I’ve started putting together a validator that’ll catch this sort of thing: https://github.com/neil-morrison44/openfpga-validator

(It’s pretty barebones at the moment but I’ll be adding more checks)
