### ISSUE TITLE
Map keyboard keys to buttons

### ISSUE THREAD

**Issue by StupidCoder** [Mazamars312/Analogue-Amiga#12]
It would be great if we could map keyboard keys to controller buttons. Some games only use a single joystick button, leaving 7 buttons on the Analogue Pocket unused. Some versions of games come with a trainer menu that requires the arrow keys and spacebar to operate. Being able to map those to the extra buttons would be amazingly useful.

More involved but even more useful would be the option to use L / R as modifiers. For example, while holding L the D-Pad acts as arrow keys, and while holding R the D-Pad, A and B buttons act as the mouse. This would make many more games playable on the go where you don't have access to a dock.

**Comment by StevenHachel** [comment]
That would not only be very useful, but also important. Some games use mouse keys for confirmations etc., or games like Turrican use the space key. Configurations for this, possibly storable as JSON per game, would be great. :)

Nice Amiga FPGA. Great work! :-)

**Comment by dfilskov** [comment]
Hear hear :)

But can't we connect a usb C keyboard directly without the dock?

**Comment by Mazamars312** [comment]
And OSD Keyboard has been built into the new core. Release soon :-)
