### ISSUE TITLE
Cannot load adfs

### ISSUE THREAD

**Issue by d3cka2d3pw** [Mazamars312/Analogue-Amiga#14]
I cannot seem to load adfs
The screen just slowly flashes and I have to hold the power button to reset the pocket.
Any help would be appreciated.

https://drive.google.com/file/d/1Uk6nDdc0GmI_55NXlZue8LYn1eEn6lYC/view?usp=drivesdk

**Comment by Mazamars312** [comment]
There are 3 things that you will need to check
Make sure you have the latest firmware
Make sure clean install from 0.0.5
Clean the cache memory in the /System folder

**Comment by d3cka2d3pw** [comment]
Ace that worked. Thank you! :)
