### ISSUE TITLE
Turrican 2 AGA - CD32 pad setting issues

### ISSUE THREAD

**Issue by AlePax** [Mazamars312/Analogue-Amiga#16]
I just can't get it working, no matter what... I tried all possible input combos in core settings and even creating a custom pad profile in the game, but buttons X, Y, L and R they just seem not to work. Any suggestions?

[https://sonicslothgames.itch.io/turrican2aga](url)

**Comment by Mazamars312** [comment]
Found what the issue was, and the next core will have this corrected
