### ISSUE TITLE
Ruff ‘n’ Tumble - Amiga.Vision freezes

### ISSUE THREAD

**Issue by ghamson** [Mazamars312/Analogue-Amiga#18]
Hey ya,

Great work on the core!

Ruff ‘n’ Tumble on the Amiga.Vision pocket HDF release freezes before it gets to the title screen.

Floppy version works without issue.

As I play around with the new core tonight I may update this issue with other games if I find them.

Thanks for all the effort!

**Comment by Mazamars312** [comment]
Yea, we have found a few games that will crash.

It looks to be a memory issue that I have introduced to it into the core. 

Working with the Amiga Vision team to determine what is causing this.

**Comment by ghamson** [comment]
That’s cool, if you get the chance to fix and you need a tester, let me know!

thanks again!

**Comment by ghamson** [comment]
Closing as another issue which has a list of games has been added.  I have added my findings to the comment of that issue.
