### ISSUE TITLE
Many games stop working with the last update

### ISSUE THREAD

**Issue by joanwitek** [Mazamars312/Analogue-Amiga#19]
Thanks for the hard work. I´ve found many gamnes thah worked properly has stopped working (Jim Power, SWIV or glitches in Risky Woods). It´s a pity because the osd keyboard is amazing. Best regards and thank you again!!!

**Comment by ghamson** [comment]
I will close my issue and add my findings here

Ruff n Tumble - loads to the point of seeing the head of the main character but never gets to the title screen.  Floppy version works with no issues for me up to level 2.

Gravity-Force - loads and plays but on completing level 1, it hangs on a black screen and never gets to level 2.  Floppy version can get to level 2.

**Comment by limi** [comment]
Adding to those:


Clown-O-Mania seems unable to proceed past the Starbyte opening graphic. 

Powermonger plays the intro, but freezes after it is complete.

**Comment by limi** [comment]
This may also be related? https://github.com/amigavision/AmigaVision/issues/109

**Comment by rsn8887** [comment]
The WHDLoad version of Jim Power on Amigavision works fine, only the .adf Version shows the graphical corruption in the background.

**Comment by rsn8887** [comment]
I tried my own WHDLoad installed hdf for Ruff'n'Tumble and it works, using same config as AmigaVision but booting my own hdf instead. No clue why it doesn't work on AmigaVision.

**Comment by limi** [comment]
I have tested the following on the upcoming version of the Pocket core (which fixes some Cache issues), and the following work fine with the AmigaVision setup as far as I can see:

* Jim Power
* Ruff n’ Tumble
* SWIV
* Risky Woods
* PowerMonger

I am terrible at Gravity Force, but I suspect that one is fixed too? Re-open if not.

Clown-O-Mania is broken on MiSTer too, we’re looking into it:
https://github.com/amigavision/AmigaVision/issues/152
