### ISSUE TITLE
Amiga vision menu font size. 

### ISSUE THREAD

**Issue by Mika73** [Mazamars312/Analogue-Amiga#20]
Is It possible get font bigger at Amiga Vision menu? Font is very small/resolution high so it’s very hard see with Analogue pocket screen.

**Comment by Mazamars312** [comment]
Saddly I need help changing the font sizes.

However, you can go into the Video.json and change the aspect ratio to the pocket screen

Just change the Aspect_h: 160
And Aspect_v: 144
And that will "Full up" the screen.

Will ask the AmigaVision guys if they can work on that as well on their side.

**Comment by Mika73** [comment]
Thank you. I try to modify that file. Is there any problem if change that? Lähetetty iPhonestaMurray Aickin ***@***.***> kirjoitti 9.6.2023 kello 2.27:﻿
Saddly I need help changing the font sizes.
However, you can go into the Video.json and change the aspect ratio to the pocket screen
Just change the Aspect_h: 160
And Aspect_v: 144
And that will "Full up" the screen.
Will ask the AmigaVision guys if they can work on that as well on their side.

**Comment by limi** [comment]
It will affect the aspect ratio and scaling for very little benefit. We are working on a "hi-res" variant for AmigaVision, and will take Pocket usage into account too — I would recommend keeping the settings as default for now, but it is of course up to you. Closing this ticket, as it's really up to us to fix in the AmigaVision launcher, not an issue with the Pocket core.
