### ISSUE TITLE
Reshoot R not running

### ISSUE THREAD

**Issue by Sebbo401** [Mazamars312/Analogue-Amiga#22]
Hi, maybe I'm just to stupid, but I created a adf file, but this game will not boot.

Reshoot R is from 2018 running on Amiga 1200, Amiga 4000 or Amiga CD32 - could this be the problem?

**Comment by limi** [comment]
For what it’s worth, this game seems to work perfectly using the https://amiga.vision setup if you don’t want to deal with all the configuration yourself.

**Comment by Sebbo401** [comment]
> For what it’s worth, this game seems to work perfectly using the https://amiga.vision setup if you don’t want to deal with all the configuration yourself.

Thanks a lot for the tip. I'm already using the amiga vision setup.

Maybe the adf-file I created is just not working.

Any clue or hint, how i can create a working adf or hdf file from my game CD?

**Comment by limi** [comment]
AmigaVision uses WHDLoad containers, you can use the following with your original media to create a WHDLoad version: 

http://www.whdload.de/games/ReshootR.html

**Comment by Sebbo401** [comment]
> AmigaVision uses WHDLoad containers, you can use the following with your original media to create a WHDLoad version:
> 
> http://www.whdload.de/games/ReshootR.html

Hi, and thanks a lot for your help. But I have no clue how to crate a WHDLoad file from a disc. Found some tutorials online, but seems mega complex. Is there kind of a simple tool to create thoses files?

**Comment by Sebbo401** [comment]
Ah! Got it - thanks a lot!
