### ISSUE TITLE
Request to allow d-pad to be remapable 

### ISSUE THREAD

**Issue by flamingoave** [Mazamars312/Analogue-Amiga#29]
Hi Mazamars312, I appreciate your excellent work on the Amiga core. I was wondering if it would be possible to implement the ability to remap the d-pad buttons as well. For Prince of Persia especially, using Up to jump is very cumbersome on the Pocket's d-pad.

**Comment by Mazamars312** [comment]
No sorry, this is a analogue firmware thing
