### ISSUE TITLE
Pocket OS 2.0 Mouse control in dock

### ISSUE THREAD

**Issue by tpm1999** [Mazamars312/Analogue-Amiga#30]
Pocket OS 2.0 seemed to fix the screen "tearing" issue with monitors connected to the dock.  But unfortunately the mouse speed issues connected to the dock seem to remain (way too fast/jerky).  Does the core need to be updated to implement any OS 2.0 mouse fix?

**Comment by davewongillies** [comment]
@tpm1999 this got fixed in https://github.com/Mazamars312/Analogue-Amiga/releases/tag/Mazamars312.Amiga.0.1.2

**Comment by tpm1999** [comment]
Just saw that update and it works great now!  Closing Issue.

**Comment by tpm1999** [comment]
Update to Amiga core for OS 2.0 has fixed the mouse issue on the few games that I have tried it with so far.
