### ISSUE TITLE
Secondary HDDs don't appear to be enabled

### ISSUE THREAD

**Issue by deanzor** [Mazamars312/Analogue-Amiga#36]
I've been trying without success to access the HDD3 and HDD4 slots. No matter what I do, I can't get DOPUS to see anything there. 

Is it possible that these are set to disabled, as they are for the default config on MISTer? 

Where would I look to check if they were enabled?

Default MISTEr config: 
 Primary Master:
    Fixed/HDD
    games/Amiga/MegaAGS.hdf
  Primary Slave:
    Fixed/HDD
    games/Amiga/MegaAGS-Saves.hdf
  **Secondary Master: Disabled
  Secondary Slave: Disabled**

**Comment by limi** [comment]
You need IDEFix97 or AtapiMagic to add support for two extra drives, as the Amiga originally did not support this. Take a look on Aminet for the software. Unrelated to the core as such, this is a software limitation.

**Comment by deanzor** [comment]
Thanks so much for replying.

My idea was to mount a hdf image of SWOS to get around the whload version being borked ATM. 

I'll look into this, cheers!
