### ISSUE TITLE
Hybris

### ISSUE THREAD

**Issue by Tinkerpete** [Mazamars312/Analogue-Amiga#37]
I think it's great that the Analogue Pocket supports an Amiga Core! Shanghai runs perfectly, but there are problems with 'Hybris'. Graphical objects like my own spaceship are not displayed correctly. It looks like Denise can't copy the 'sprites' correctly. Is this more a problem with the settings or do I have to wait until Denise can also be mapped correctly in the FPGA?

**Comment by rsn8887** [comment]
Works fine for me using default settings (AmigaVision) apart from the small known corruption of "Score" letters on the top left:

![20240120_203528](https://github.com/Mazamars312/Analogue-Amiga/assets/13071547/53cf45f1-d345-4295-bbe9-e8ad3a2711b6)

**Comment by Tinkerpete** [comment]
When I do 'Reset alll to Default' and then insert the 'Hybris' floppy disk with 'Load Floppy drive 0' and do 'CPU Reset', it comes up in red color:

Software failure

It also seems that the same error message does not always appear and sometimes disks are recognized with 'CHecksum error' or similar. All in all, the behavior seems to be inconsistent, which indicates that the memory is not properly initialized.

Aber es ist schön zu wissen, das es grundsätzlich funktionieren könnte!!!

**Comment by Tinkerpete** [comment]
I may have solved the problem!

In Bios I have 

**amiga-os-120**

and for System Configuration I have

**OG/PAL/Std**

and the graphical problems have disappeared!

**Comment by Mazamars312** [comment]
Yes, I find many games have some weird requirements and settings on the amiga.

Some of them also will not work with the 68020 cpu as well. so keep that in mind.

**Comment by limi** [comment]
When using ADF images, 90% of the time they are for the Amiga 500, so will need PAL, ECS and 68000 selected. Part of the reason AmigaVision exists is to handle all the Amiga-specific configurations and details for you.
