### ISSUE TITLE
How I change between HDF images? 

### ISSUE THREAD

**Issue by Mika73** [Mazamars312/Analogue-Amiga#39]
How I change between HDF images? 

I try change MegaAGS Pocket to full size MegaAGS but couldn’t find full HDF file from Archive. 

So I download Paul Vincent Amiga AGS and now try use that HDF image. 

About Amiga vision I could find two options Archive that I currently have, but MegaAGS package MegaAGS.HDF was just little over 1gb size and package had also many other ADF files. Full HDF should be lot bigger.

**Comment by StevenHachel** [comment]
```
This core works best with the [AmigaVision](https://amiga.vision/) configurations.

Will only work on Analogue OS firmware 2.1 and now works with the default AmigaVision harddrive image, no Pocket-specific version required anymore!

Support for >4GB hard drive images LBA48 has been turned on in the MPU and Analogue Firmware and the data.json file now has this as the MegaAGS.hdf as the default hard drive image to load.

If you are upgrading from an earlier version of the Amiga core with AmigaVision installed: MegaAGS-Pocket.hdf is no longer referenced in the data.json file, so if you want to use the smaller setup instead of downloading the full version, just rename the image file. But we recommend getting the full version to have access to all the games and demos.
```

[](https://github.com/Mazamars312/Analogue-Amiga) Have fun. :-)

**Comment by Mika73** [comment]
Hi Thank you. I have Analogue Pocket OS 2.1 updated. Problem is that I can’t find full version of working MegaAGS.hdf. I have pocket version that’s renamed now. I try download full with Amigavision download that leads to Archive. There I can find two downloads. Pocket and MegaAGS. Problem is that when I try download MegaAGS.HDF it was just little over 1gb. Way too small. Pocket was over 3GB. archive.orgI did try download this file. It was only little over 1gb and it’s only one I can find. Lähetetty iPhonestaStevenHachel ***@***.***> kirjoitti 21.1.2024 kello 19.04:﻿
This core works best with the [AmigaVision](https://amiga.vision/) configurations.

Will only work on Analogue OS firmware 2.1 and now works with the default AmigaVision harddrive image, no Pocket-specific version required anymore!

Support for >4GB hard drive images LBA48 has been turned on in the MPU and Analogue Firmware and the data.json file now has this as the MegaAGS.hdf as the default hard drive image to load.

If you are upgrading from an earlier version of the Amiga core with AmigaVision installed: MegaAGS-Pocket.hdf is no longer referenced in the data.json file, so if you want to use the smaller setup instead of downloading the full version, just rename the image file. But we recommend getting the full version to have access to all the games and demos.

 Have fun. :-)

**Comment by Mazamars312** [comment]
To change the HDF file you need to change the entry in the /Cores/Mazamars312.Amiga/data.json at line 39 for IDE drive 0 (https://github.com/Mazamars312/Analogue-Amiga/blob/3558104bd9a04d4d1858126857c25560087a214f/dist/Cores/Mazamars312.Amiga/data.json#L39) to the file name of the image. There is no way to do this change while running the core due to how media is changed in the analogue and a full reset is required of the core.

The full image is out there, just search for it and change the data.json file as required.

**Comment by Mika73** [comment]
Thanks. I got Amiga vision working. First time was problem that at archive I try only load MegaAGS.HDF from inside package because that was only I really needed. It was just 1Gb after download. I needed download whole 7z package and after unzip file was correct size over 9gb. It’s very nice collection of Amiga stuff. Lähetetty iPhonestaMurray Aickin ***@***.***> kirjoitti 23.1.2024 kello 6.16:﻿
To change the HDF file you need to change the entry in the /Cores/Mazamars312.Amiga/data.json at line 39 for IDE drive 0 (https://github.com/Mazamars312/Analogue-Amiga/blob/3558104bd9a04d4d1858126857c25560087a214f/dist/Cores/Mazamars312.Amiga/data.json#L39) to the file name of the image. There is no way to do this change while running the core due to how media is changed in the analogue and a full reset is required of the core.
The full image is out there, just search for it and change the data.json file as required.
