### ISSUE TITLE
Was working, but something went wrong...

### ISSUE THREAD

**Issue by bbond007** [Mazamars312/Analogue-Amiga#8]
Hi,

I installed this core and was able to run a few scene demos successfully initially.

I then added some games, and now whenever I try select "Load Floppy drive 0" the screen starts flashing/fading on and off (I'd say about 1 second interval) and I have to power off the pocket as its stuck.

I tried resetting the Amiga config and replaced all the core files, but still no longer works. 

Also For testing, I also tried just moving the "GAMES" folder I added to the root of the SD card so they are not in the amiga/common folder anymore as it did work prior to adding the games. 

EDIT:
also tried replacing the Kickstart ROM with the one from my MiSTer.

Thank you very much for making this core...

Any idea oh how to make it work again? 

Thanks!

**Comment by terminator2k2** [comment]
is this the bug in the OS where if you delete the last played game then retry the core the  pocket OS goes off on one and just flashes black and white? not sure if its just deleting the last played game , but ive had this on all cores if you delete files from a core you just used , then try re-loading the core again.  ive found you can either put the last played game back on and retry or delete the cache files in the system folder (think it's system lol). Re-doing the sd card should also solve it

**Comment by bbond007** [comment]
> What version of pocket firmware are you using?

pocket_firmware_B_8.bin

> is this the bug in the OS where if you delete the last played game then retry the core the pocket OS goes off on one and just flashes black and white? 

Looks like that was the issue...

Temporarily restoring the path to the last demo I tried fixed the problem :)

Thanks!

**Comment by ifighftdragons** [comment]
This issue shouldn't be closed, as it hasn't been properly fixed.

**Comment by terminator2k2** [comment]
> This issue shouldn't be closed, as it hasn't been properly fixed.

its a Analogue OS issue not a core issue,This problem happens with all cores. so its not like Maz can fix the problem.
