### ISSUE TITLE
Flashing screen when attempting to load Floppy Drive 0

### ISSUE THREAD

**Issue by stevefish** [Mazamars312/Analogue-Amiga#9]
I've provided a quick video and outlined what I'm experiencing [here in a Reddit post](https://www.reddit.com/r/AnaloguePocket/comments/zf3lcp/any_idea_why_this_happens_when_i_try_to_load/) along with some follow up testing info in the comments that seems to have fixed the problem I'm experiencing - however tentatively.

Basically, something is causing my screen to fade in and out when I try to load Floppy Drive 0. It's possible the hidden ._ files created by MacOS are contributing to the problem. The only solution I've found once this problem starts is to delete all files on my SD card associated with this core and reinstall fro scratch - being careful to delete all ._ files before using the core again. 

If I can assist in troubleshooting this problem, just let me know.

**Comment by Mazamars312** [comment]
What version of pocket firmware are you using?

**Comment by Mazamars312** [comment]
There could be something from here that could be causing your issue https://github.com/Mazamars312/Analogue-Amiga/issues/8

**Comment by ifighftdragons** [comment]
Having the exact same issue, except I can't resolve it.
Tried deleting the core completely, and do a clean reinstall. No use.
Whenever I load Floppy Disk 0, the Pocket needs to be hard rebooted.

I'm on a PC, and have no hidden files.
I also can't recreate the game folder directory, because I don't remember which game it even was.

As of right now, the core is completely broken for me.

**Comment by stevefish** [comment]
After you wipe the core and reinstall, are you also loading up a bunch of ADFs? If so, you might try putting only one on your SD card after reinstalling and see if that one works. Also, when you're removing the core, make sure you're also deleting the related files in all four folders: Assets, Cores, Platforms, and Settings.

**Comment by ifighftdragons** [comment]
> After you wipe the core and reinstall, **_are you also loading up a bunch of ADFs?_** If so, you might try putting only one on your SD card after reinstalling and see if that one works. Also, when you're removing the core, make sure you're also deleting the related files in all four folders: Assets, Cores, Platforms, and Settings.

Not sure what you mean by "loading up a bunch of ADFs?

Do you mean if I put the games in the correct folder, after a clean install? 
**Answer:** I've tried both not putting any games in assets, and putting just one, or a couple games there.

Or do you mean if I try to load the games to play? 
**Answer:** Impossible. Can't load anything in Floppy Disk 0 without the core crashing.

I have made sure I've deleted every related file and folder, in Assets, Cores, Platforms, and Settings.

**Comment by ifighftdragons** [comment]
Found a temporary fix:

You need to delete the browser MRU file in the **_Systems_** folder.
It acts as a memory file for the browser.

**Comment by terminator2k2** [comment]
probably related to :

https://discord.com/channels/834264850230018058/1002764115271491665/1045851452070973542

Analogue OS issue
